import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../../constants/theme";

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.sm,
    maxHeight: "88%",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  title: { fontSize: 14, fontWeight: "800" },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  content: { paddingBottom: SPACING.sm, gap: 8 },
  avatarRow: { alignItems: "center", marginBottom: 4 },
  avatar: { width: 68, height: 68, borderRadius: RADIUS.pill },
  avatarFallback: {
    width: 68,
    height: 68,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    borderWidth: 1,
    borderRadius: RADIUS.md,
    minHeight: 42,
    paddingHorizontal: 12,
    fontSize: 12,
  },
  inputMultiline: {
    minHeight: 78,
    paddingTop: 10,
    textAlignVertical: "top",
  },
  grid: { flexDirection: "row", gap: 8 },
  half: { flex: 1 },
  fieldLabel: { marginTop: 2, fontSize: 11, fontWeight: "700" },
  roleWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  roleChip: {
    minHeight: 32,
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  roleChipText: { fontSize: 11, fontWeight: "700" },
  statusRow: {
    minHeight: 46,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusText: { fontSize: 12, fontWeight: "600" },
  error: { fontSize: 11, fontWeight: "600" },
  footer: { flexDirection: "row", gap: 8, marginTop: SPACING.sm },
  button: {
    flex: 1,
    minHeight: 42,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { fontSize: 12, fontWeight: "700" },
});
