import { StyleSheet } from "react-native";
import { RADIUS, SPACING, softShadow } from "../../constants/theme";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  container: { paddingBottom: 120, gap: SPACING.md },
  section: { paddingHorizontal: SPACING.md, gap: SPACING.sm },
  selectorCard: {
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    padding: 4,
    flexDirection: "row",
    alignItems: "center",
    ...softShadow,
  },
  selectorBtn: {
    minHeight: 38,
    flex: 1,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 8,
  },
  selectorText: { fontSize: 12, fontWeight: "700" },
  selectorDivider: { width: 1, height: 22, marginHorizontal: 5 },
  selectorPicker: { flex: 1.1 },
  stats: { flexDirection: "row", gap: SPACING.sm },
  trendCard: {
    borderWidth: 1,
    borderRadius: RADIUS.xl,
    padding: 14,
    gap: 10,
    ...softShadow,
  },
  trendHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  trendTitle: { fontSize: 17, fontWeight: "700" },
  rangePill: { flexDirection: "row", gap: 8, borderRadius: RADIUS.md, paddingHorizontal: 8, paddingVertical: 5 },
  rangeText: { fontSize: 10, fontWeight: "700" },
  chartArea: { height: 120, borderRadius: RADIUS.lg, overflow: "hidden", justifyContent: "flex-end" },
  curveOne: { position: "absolute", width: 72, height: 3, borderRadius: 6, left: 10, bottom: 44, transform: [{ rotate: "-18deg" }] },
  curveTwo: { position: "absolute", width: 66, height: 3, borderRadius: 6, left: 68, bottom: 55, transform: [{ rotate: "20deg" }] },
  curveThree: { position: "absolute", width: 64, height: 3, borderRadius: 6, left: 126, bottom: 47, transform: [{ rotate: "-24deg" }] },
  curveFour: { position: "absolute", width: 68, height: 3, borderRadius: 6, left: 184, bottom: 58, transform: [{ rotate: "24deg" }] },
  curveFive: { position: "absolute", width: 70, height: 3, borderRadius: 6, left: 242, bottom: 47, transform: [{ rotate: "-18deg" }] },
  peakTag: { position: "absolute", top: 10, left: "42%", borderRadius: 8, paddingHorizontal: 6, paddingVertical: 4 },
  peakText: { color: "#fff", fontSize: 10, fontWeight: "700" },
  weekRow: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 4 },
  weekLabel: { fontSize: 10, fontWeight: "600" },
  hotelList: { gap: SPACING.sm },
  empty: { fontSize: 12, fontWeight: "600" },
});
