import { StyleSheet } from "react-native";
import { RADIUS, SPACING, softShadow } from "../../constants/theme";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  container: { paddingBottom: 120, gap: SPACING.md },
  section: { paddingHorizontal: SPACING.md, gap: SPACING.sm },
  selectorCard: {
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    padding: 4,
    flexDirection: "row",
    alignItems: "center",
    ...softShadow,
  },
  selectorBtn: {
    minHeight: 38,
    flex: 1,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 8,
  },
  selectorText: { fontSize: 11, fontWeight: "700" },
  selectorDivider: { width: 1, height: 22, marginHorizontal: 5 },
  selectorPicker: { flex: 1.1 },
  stats: { flexDirection: "row", gap: SPACING.sm },
  trendCard: {
    borderWidth: 1,
    borderRadius: RADIUS.xl,
    padding: 14,
    gap: 10,
    ...softShadow,
  },
  trendHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  trendTitle: { fontSize: 15, fontWeight: "700" },
  rangePill: { flexDirection: "row", gap: 8, borderRadius: RADIUS.md, paddingHorizontal: 8, paddingVertical: 5 },
  rangeText: { fontSize: 10, fontWeight: "700" },
  chartArea: { height: 120, borderRadius: RADIUS.lg, overflow: "hidden" },
  lineSegment: { position: "absolute", height: 2, borderRadius: RADIUS.pill },
  point: { position: "absolute", width: 6, height: 6, borderRadius: RADIUS.pill },
  peakTag: { position: "absolute", top: 10, left: "42%", borderRadius: 8, paddingHorizontal: 6, paddingVertical: 4 },
  peakText: { color: "#fff", fontSize: 10, fontWeight: "700" },
  weekRow: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 4 },
  weekLabel: { fontSize: 10, fontWeight: "600" },
  hotelList: { gap: SPACING.sm },
  empty: { fontSize: 11, fontWeight: "600" },
});
