import { StyleSheet } from "react-native";
import { RADIUS, SPACING, softShadow } from "../../constants/theme";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  container: { paddingBottom: 120, gap: SPACING.md },
  section: { paddingHorizontal: SPACING.md, gap: SPACING.sm },
  pickers: { gap: SPACING.sm, flexDirection: "row" },

  detailHeader: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  detailTitleWrap: { flex: 1 },
  detailTitle: { fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  detailSub: { marginTop: 2, fontSize: 11, fontWeight: "600" },

  primaryMetric: {
    borderRadius: RADIUS.xl,
    padding: 16,
    minHeight: 128,
    justifyContent: "space-between",
    ...softShadow,
  },
  metricHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  metricLabel: { color: "#cfe0ff", fontSize: 10, fontWeight: "700", letterSpacing: 0.4 },
  metricValue: { color: "#fff", fontSize: 24, fontWeight: "800", letterSpacing: -0.5 },
  metricHint: { color: "#b8d1ff", fontSize: 11, fontWeight: "600" },

  metricRow: { flexDirection: "row", gap: SPACING.sm },
  secondaryMetric: {
    flex: 1,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    padding: 14,
    minHeight: 112,
    justifyContent: "space-between",
    gap: 8,
    ...softShadow,
  },
  secondaryLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 0.4 },
  secondaryValue: { fontSize: 20, fontWeight: "800", letterSpacing: -0.4 },
  secondaryHint: { fontSize: 11, fontWeight: "500" },
  progressTrack: { height: 6, borderRadius: RADIUS.pill, marginTop: 4 },
  progressBar: { height: 6, borderRadius: RADIUS.pill },

  detailTabs: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    padding: 4,
    gap: 4,
  },
  detailTabBtn: {
    flex: 1,
    minHeight: 34,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  detailTabBtnActive: {},
  detailTabText: { fontSize: 11, fontWeight: "700" },

  toolbarRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  addMiniBtn: {
    minHeight: 32,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  addMiniText: { color: "#fff", fontSize: 10, fontWeight: "700" },

  formCard: {
    borderWidth: 1,
    borderRadius: RADIUS.xl,
    padding: 12,
    gap: 8,
  },
  input: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    fontSize: 12,
  },
  rowSplit: { flexDirection: "row", gap: 8 },
  halfInput: { flex: 1 },
  inputMultiline: {
    minHeight: 74,
    paddingTop: 10,
    textAlignVertical: "top",
  },
  fieldLabel: { fontSize: 11, fontWeight: "700" },
  inlineHint: { fontSize: 11, fontWeight: "500" },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    minHeight: 30,
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  chipActive: {},
  chipText: { fontSize: 10, fontWeight: "700", textTransform: "capitalize" },
  switchRow: {
    minHeight: 42,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  switchLabel: { fontSize: 12, fontWeight: "600" },
  errorText: { fontSize: 11, fontWeight: "600" },
  submitBtn: {
    minHeight: 40,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: { color: "#fff", fontSize: 12, fontWeight: "700" },

  serviceGrid: { gap: SPACING.sm },
  serviceCard: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    minHeight: 72,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  serviceImage: { width: 54, height: 54, borderRadius: 12 },
  serviceFallback: {
    width: 54,
    height: 54,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceBody: { flex: 1 },
  serviceTitle: { fontSize: 13, fontWeight: "700" },
  serviceMeta: { marginTop: 2, fontSize: 11, fontWeight: "500" },
  statusPill: {
    borderRadius: RADIUS.pill,
    paddingHorizontal: 10,
    minHeight: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: { fontSize: 10, fontWeight: "700", textTransform: "uppercase" },

  foodList: { gap: SPACING.sm },
  foodCard: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    padding: 10,
    gap: 6,
  },
  foodHead: { flexDirection: "row", alignItems: "center", gap: 10 },
  foodIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  foodBody: { flex: 1 },
  foodTitle: { fontSize: 13, fontWeight: "700" },
  foodMeta: { fontSize: 11, fontWeight: "500" },

  list: { gap: SPACING.sm, paddingBottom: 4 },
  roomCard: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  infoTitle: { fontSize: 13, fontWeight: "700" },
  infoSub: { marginTop: 2, fontSize: 11, fontWeight: "500" },

  amenityGroup: {
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    paddingHorizontal: 12,
    paddingTop: 10,
    overflow: "hidden",
  },
  amenityGroupTitle: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  amenityRow: {
    minHeight: 48,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  amenityInfo: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1, paddingRight: 8 },
  amenityName: { fontSize: 12, fontWeight: "600" },

  roomHero: {
    borderWidth: 1,
    borderRadius: RADIUS.xl,
    overflow: "hidden",
    minHeight: 180,
  },
  roomHeroImage: { width: "100%", height: 188 },
  roomHeroFallback: {
    width: "100%",
    height: 188,
    alignItems: "center",
    justifyContent: "center",
  },
  roomFacts: { flexDirection: "row", gap: SPACING.sm },
  roomFactCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    padding: 12,
    minHeight: 86,
    justifyContent: "center",
    gap: 4,
  },
  roomFactLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 0.4 },
  roomFactValue: { fontSize: 16, fontWeight: "800" },

  bookingCard: { borderWidth: 1, borderRadius: RADIUS.lg, padding: 12, gap: 3 },

  emptyHint: { fontSize: 11, marginTop: 4 },
});
