import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: { flexGrow: 1, paddingHorizontal: SPACING.md, paddingBottom: SPACING.xl, paddingTop: SPACING.sm },
  topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: SPACING.lg },
  topTitle: { fontSize: 28, fontWeight: "800", letterSpacing: -0.4 },
  topSpacer: { width: 22 },
  hero: { alignItems: "center", marginTop: 4, marginBottom: SPACING.lg },
  logoIconWrap: { width: 74, height: 74, borderRadius: 22, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  brand: { fontSize: 32, fontWeight: "800", letterSpacing: -0.5 },
  subtitle: { marginTop: 7, fontSize: 13, textAlign: "center", lineHeight: 19 },
  form: { gap: 8 },
  label: { marginTop: 4, marginBottom: 3, fontSize: 14, fontWeight: "700" },
  inputWrap: {
    height: 50,
    borderRadius: RADIUS.lg,
    paddingHorizontal: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  input: { flex: 1, fontSize: 16, paddingVertical: 0 },
  passwordWrap: {
    height: 50,
    borderRadius: RADIUS.lg,
    paddingHorizontal: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  passwordInput: { flex: 1, fontSize: 16, paddingVertical: 0 },
  forgotBtn: { alignSelf: "flex-end", marginTop: 2 },
  forgotText: { fontSize: 14, fontWeight: "700" },
  error: { marginTop: 4, fontSize: 13, fontWeight: "600" },
  button: {
    marginTop: 2,
    minHeight: 54,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  buttonText: { color: "#fff", fontSize: 20, fontWeight: "700" },
  secureCard: {
    marginTop: 24,
    minHeight: 92,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  secureIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  secureDivider: { width: 1, height: 26, marginHorizontal: 14, backgroundColor: "rgba(36,99,235,0.2)" },
  secureText: { fontSize: 14, fontWeight: "700" },
  footer: { marginTop: 24, gap: 10, alignItems: "center" },
  footerRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  footerLink: { fontSize: 12, fontWeight: "600" },
  footerDot: { fontSize: 12, fontWeight: "600" },
  footerCopy: { fontSize: 10, fontWeight: "700", letterSpacing: 1 },
});
