import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../../constants/theme";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  container: { paddingBottom: 120, gap: SPACING.md },

  header: {
    minHeight: 62,
    borderBottomWidth: 1,
    paddingHorizontal: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  saveText: { fontSize: 14, fontWeight: "700" },

  profileWrap: {
    alignItems: "center",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
    borderBottomWidth: 1,
  },
  avatarWrap: { position: "relative" },
  avatar: { width: 96, height: 96, borderRadius: RADIUS.pill },
  avatarFallback: {
    width: 96,
    height: 96,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  editAvatarBtn: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    borderRadius: RADIUS.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  name: { marginTop: 10, fontSize: 20, fontWeight: "800" },
  roleRow: { marginTop: 6, flexDirection: "row", alignItems: "center", gap: 8, width: "100%", justifyContent: "center" },
  roleBadge: { borderRadius: RADIUS.pill, paddingHorizontal: 10, paddingVertical: 5 },
  roleText: { fontSize: 10, fontWeight: "700", letterSpacing: 0.7 },
  roleDot: { fontSize: 12, fontWeight: "700" },
  email: { fontSize: 12, fontWeight: "600", flexShrink: 1 },

  groupLabel: {
    marginHorizontal: SPACING.md,
    marginTop: 6,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  groupCard: {
    marginHorizontal: SPACING.md,
    borderWidth: 1,
    borderRadius: RADIUS.xl,
    overflow: "hidden",
  },
  groupRow: {
    minHeight: 58,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowBorder: { borderBottomWidth: 1 },
  rowLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  settingTitle: { fontSize: 12, fontWeight: "600" },
  rowValue: { fontSize: 12, fontWeight: "600" },

  logout: {
    marginHorizontal: SPACING.md,
    marginTop: SPACING.sm,
    minHeight: 50,
    borderRadius: RADIUS.xl,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexDirection: "row",
  },
  logoutText: { fontSize: 14, fontWeight: "700" },
  footerCopy: { textAlign: "center", fontSize: 11, fontWeight: "500", marginTop: SPACING.sm },
});
